---

# System variables
box_url: https://github.com/ib3ltd/ib3_centos/raw/master/ib3-drupal-1.0.1.box
box: "ib3-drupal-1.0.1"

ip: "192.168.33.10"
memory: 2048
cpus: 1
hostname: #HOST#

# Synced folders
folders:
  - map: .
    to: /var/www/vhosts/#HOST#
  - map: vagrant
    to: /vagrant

# nginx and php-fpm pool
sites:
  - map: #HOST#
    to: /var/www/vhosts/#HOST#/html

# Vagrant sync options
sync_options:
  :type: virtualbox
  :owner: ib3client
  :group: nginx

# Databases and users
databases:
  - name: #DATABASE#
    username: #USER#
    password: #PASSWORD#
    type: MySQL

# Root database password
dbrootpass: skippy28
